services:
  # ---- Backend Flask API ----
  - type: web
    name: task-manager-backend
    env: docker
    repo: https://github.com/Deependra-Bhatt/task-management-system
    branch: main
    rootDir: backend
    dockerfilePath: ./backend/Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: MONGO_URI
        fromDatabase:
          name: task-manager-db
          property: connectionString
      - key: JWT_SECRET_KEY
        value: jwt-super-secret-render
      - key: SECRET_KEY
        value: default_secret_key
    healthCheckPath: /

  # ---- Frontend React App ----
  - type: static
    name: task-manager-frontend
    repo: https://github.com/Deependra-Bhatt/task-management-system
    branch: main
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: build
    autoDeploy: true

databases:
  # ---- MongoDB (Managed) ----
  - name: task-manager-db
    databaseName: task_management_db
    plan: free
    user: admin
    ipAllowList: [] # Publicly accessible within Render internal network
